# Generated by Django 2.1.2 on 2018-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tggs',
            new_name='tags',
        ),
    ]
